### ISSUE TITLE
EDICTOR and 3_alignment.py

### ISSUE THREAD

**Issue by Juunlee** [lexibank/deepadungpalaung#10]
Daniel and I were able to put files in the EDICTOR and see the results. For D_Deepadung_partial.tsv, 100 concepts were attested with 1586 rows. However, when we converted D_Deepadung_aligned.tsv to EDICTOR form, there were only 28 concepts with 164 rows. There was a significant decrease in the number of concepts and we were not sure why. 

We adapted 3_alignment.py directly from work-flow paper. (The code is shown below.) Is sinopy a good python library when analyzing segments for Deepadung_files? We were not sure what to use instead. 

    from sinopy import segments
    from lingpy import *
    from lingrex.align import template_alignment
    from sys import argv

    if 'all' in argv:
        fname='A_Deepadung_'
    else:
        fname='D_Deepadung_'

    alms = Alignments(fname+'partial.tsv', ref='cogids')
    alms.add_entries(
            'structure',
            'tokens',
            lambda x: basictypes.lists(
                ' + '.join([' '.join(y) for y in segments.get_structure(
                    x)]))
            )
    print('[i] added segments')
    D = {0: [c for c in alms.columns]}
    for idx, tokens, structure in alms.iter_rows('tokens', 'structure'):
        if len(tokens.n) != len(structure.n):
            print('[!!!]', tokens, structure)
        elif len(tokens) != len(structure):
            print('[!]', tokens, structure)
        else:
            D[idx] = alms[idx]
    alms = Alignments(D, ref='cogids')

    template_alignment(alms,
                       ref='cogids',
                       template='imnct+imnct+imnct+imnct+imnct+imnct',
                       structure = 'structure',
                       fuzzy=True,
                       segments='tokens')

    alms.output('tsv', filename=fname+'aligned', prettify=False)

**Comment by LinguList** [comment]
This is obvious, since you have not tested the STRUCTURE. The structure
component in the alignment script is only working with SEA languages
with tones. But since you don't have tones, the algorithm does not work
here.

**Comment by LinguList** [comment]
```python
from lingpy import *
from sys import argv

if 'all' in argv:
    fname='A_Deepadung_'
else:
    fname='D_Deepadung_'

alms = Alignments(fname+'partial.tsv', ref='cogids')
alms.align()
alms.output('tsv', filename=fname+'aligned', prettify=False)
```

**Comment by LinguList** [comment]
that's the code you need.

**Comment by danbriggs** [comment]
3_alignment.py is working well now. However, I do not know how to remove reliance on structure from code such as the one I found in 4_crosssemantic.py from workflow-paper:

    from lingpy import *
    from lingrex.colex import find_colexified_alignments, find_bad_internal_alignments
    from lingrex.align import template_alignment
    from sys import argv

    if 'all' in argv:
        fname='../output/A_Deepadung_'
    else:
        fname='../output/D_Deepadung_'


    alms = Alignments(fname+'aligned.tsv', ref='cogids')
    print('[i] search for bad internal alignments')
    find_bad_internal_alignments(alms)

    print('[i] search for colexified alignments')
    find_colexified_alignments(
            alms,
            cognates='cogids',
            segments='tokens',
            ref='crossids'
            )

    # re-align the data
    print('[i] re-align the data')
    template_alignment(alms,
                       ref='crossids',
                       template='imnct+imnct+imnct+imnct+imnct+imnct',
                       structure = 'structure',
                       fuzzy=True,
                       segments='tokens')

    alms.output('tsv', filename=fname+'crossids', prettify=False)

I tried removing the keyword argument structure (this has no effect, as its default is 'structure' anyway in template_alignment() from lingrex/align.py), I tried changing it to None; I also do not understand the purpose of 'imnct' in template.

**Comment by LinguList** [comment]
```python
from lingpy import *
from lingrex.colex import find_colexified_alignments, find_bad_internal_alignments
from lingrex.align import template_alignment
from sys import argv

if 'all' in argv:
    fname='../output/A_Deepadung_'
else:
    fname='../output/D_Deepadung_'


alms = Alignments(fname+'aligned.tsv', ref='cogids')
print('[i] search for bad internal alignments')
find_bad_internal_alignments(alms)

print('[i] search for colexified alignments')
find_colexified_alignments(
        alms,
        cognates='cogids',
        segments='tokens',
        ref='crossids'
        )

# re-align the data
print('[i] re-align the data')
alms = Alignments(alms, ref='crossids')
alms.align()

alms.output('tsv', filename=fname+'crossids', prettify=False)
```

**Comment by danbriggs** [comment]
This works well. But I'm curious: would it be worth it to add a "structure" judgment back in? All the words in all the Palaungic languages seem to follow the same template you, Wu, and Bodt outlined in the _Computer-Assisted Language Comparison_ paper, just without the tones.

And rereading that paper with Junsung tonight, we came to understand what "imnct" means, so shouldn't "imnc" be able to work for this somehow?

**Comment by LinguList** [comment]
I am afraid, in this case, you would have to manually set the plus for
morpheme boundaries. This might enhance the cognate detection. But I do
not know if we find a way to do the splitting automatically. But we need
this, the morpheme boundary, before we can do template alignment.

**Comment by danbriggs** [comment]
I think it would be a good idea, especially since in several cases the word attested variously has a space and doesn't in the various languages, and there are no or almost no other differences between them.

But where would be the place to do the work of adding spaces? cldf/forms.csv, cldf/cognates.csv, or the original raw/100item-phylo.Sheet1.csv?

I will assign this to Junsung.

**Comment by danbriggs** [comment]
Junsung and I have started adding plus signs between syllables in the entires of the segments column of cldf/forms.csv by hand. We have also been turning diphthongs into single segments.

In the future, I would be interested in developing a script to do this automatically. I don't think it would be that hard to make it attempt to apply imnc format across a word.

**Comment by LinguList** [comment]
What does it mean to modify diphthongs? They are treated already as monopthongs in the lingpy sound class system. Do you mean you make `a u` to `au`? I hope you did not delete any sounds. If you want me to check, you could send me edited examples via email, or upload them to a folder `analyses`.

**Comment by danbriggs** [comment]
> Do you mean you make a u to au

Yes; we looked at chenhmongmien/cldf/forms.csv and deepadungpalaung/cldf/forms.csv and noticed that that e.g. what was "a u" in the latter is "au" in the former, and figured that putting them together manually would likely be required to put them through an "imnc" template.

We haven't altered the file in situ; Junsung is creating an alternate file to test with the *imnc* template, and taking notes along the way.

Out of the first 600 of the 1600 attestations, the only word that might arguably be tough to fit into this template is the word for "cloud" in half the languages, /ŋʔuʔ/. And the only word where we are considering changing anything is "root," which is given as /riahːi/ in some languages and /riah hi/, segmentable, in others. So we're thinking of changing /riahːi/ to /riah hi/. But if we shouldn't do anything like that, we won't; and we can easily just add "+" signs without making the diphthongs single segments or doing anything else, if that's a better idea.

**Comment by LinguList** [comment]
But the merging of dipthongs is usually handled by orthography profiles: you just write:

```
Grapheme   IPA
au    au
a     a
u     u
```

This will handle it.

**Comment by LinguList** [comment]
/ŋʔuʔ/ is in fact easy to handle by writing ŋʔ as ŋ + superscript-ʔ

But this should go into the orthography profile. 

As to riahhi etc: again, it seems this is best done already in the orthography profile, where you can insert the full sequence and re-segment it. Much more transparend than doing this independently, right?

In fact, if you figure the forms that are unsplit are just a few (in the 100), you could add them all to the orthography profile, and we'd automatically split them. 

```
Grapheme IPA
^riahːi$    r i a h + h i
```

You see? Just remember: `^` is beginning of word, `$` is end, so you explicitly mark that it is a full word.

**Comment by danbriggs** [comment]
Thank you! We will try this approach during our next session.

**Comment by danbriggs** [comment]
We implemented this method in our session tonight, and the results were very good. We also had the occasion to look at all the words attested in all the Palaungic languages, and see how a choice of what to add to etc/orthography.tsv affected cldf/forms.csv.

Almost every multisyllabic word attested in each language adds to the evidence that syllables are morphemes in Palaungic languages (at least among the 100 basic words), and cognacy is best served on a morpheme-by-morpheme, rather than whole word, basis. Curiously, the only places where it did not add to the evidence were when the first syllable was /ka/~/kә/.

There are two possibilities for a syllable in Palaungic languages (at least among these 100 concepts): i[m]n[c], or lone nasal. The lone nasal has only been seen as the first syllable of a word, and it can be cognate with a syllable that has that nasal as the final consonant.

Geminated consonants only occur when the final consonant of one syllable matches the initial consonant of the next.

With these ideas in mind, we added a few rows to orthography.tsv:

    oj$	o j
    ej$	e j
    au$	a u		
    au	au
    ou	ou
    oj	oi
    ɛa	ɛa
    əa	əa
    ai	ai
    ej	ei

We first tried doing oj -> oj and ej -> ej, but transcription.md said the segments /oj/ and /ej/ are unrecognized.

We also changed the decision for a couple other rows; we decided on "hh" -> "h h" and "kk" -> "k k" on the basis of the observation about geminates above. I will push etc/orthography.tsv now and the diff will show anything I forgot to mention.

The only sequence of symbols for which the best approach is not clear is when "ria" appears after an initial consonant.

We forgot (or maybe we never knew) how to get the EXAMPLES, LANGUAGES, FREQUENCY, and CODEPOINTS columns to populate themselves in orthography.tsv. So they are blank for the new rows.

I'll also push cldf/forms.csv but as cldf/forms_new.csv, in case there's anything you don't like about the process or the result.

If you think this is a good enough orthography.tsv for a final result, I will ask Junsung to start putting the pluses in manually for syllable boundaries.

**Comment by LinguList** [comment]
You are allowed to **rewrite* the orthography. Obviously "oj" is "oi". So I suggest: rewrite as oj -> oi, to have a dipthong.

No worry about the examples in orthoprofile. They can be discarded. Please push as `forms.csv`, we have git, and version control, right? So we can always go back.

But maybe make a pull request, so I can review?

**Comment by danbriggs** [comment]
Ok! It's good to know no information is being lost from changing i to j or vice versa. I will create a new branch and then make a pull request now.

**Comment by danbriggs** [comment]
The "Pull requests" page now mentions it, but doesn't call it an open or closed pull request.

**Comment by danbriggs** [comment]
I was able to turn it into a full-fledged pull request.

Reviewing forms.csv myself, I think the only things I would change would be to extend the pattern of "oj" -> "oi" to all the rest of the vowels, with a special excpetion for BanPaw "mahujə" (heart), delete the rule "jh$" -> "j̊", and add rules analogously for "aw" -> "au" etc.

Edit: no need for all that. Just three lines:
    ai$	a j
    ej	ei
    ei	ei

**Comment by danbriggs** [comment]
With my help, Junsung has added 176 rules at lines 28 to 203 of orthography.tsv to allow it to do syllable segmentation automatically. We checked the 1585 entries together, and believe no words are oversegmented, and all syllables follow the imnc template.

**Comment by LinguList** [comment]
very nice.
